export type MelaLocale = "es" | "en";

const es = {
  nav: { work: "Trabajo", pkg: "Paquetes", proc: "Proceso", about: "Sobre mí", faq: "Preguntas", cta: "Cotizar" },
  hero: {
    eyebrow: "Wedding content creator · República Dominicana & destino",
    titleA: "Tu boda, publicada ",
    titleEm: "antes",
    titleB: " de que termine la fiesta.",
    lede: "Grabo tu día en vertical, con el ojo de una invitada y el criterio de una editora. Nada de esperar seis meses: el material llega a tus manos al día siguiente, listo para publicar.",
    cta1: "Escribirme por WhatsApp",
    cta2: "Ver paquetes y precios",
    specs: ["9:16 vertical nativo", "60–120 clips por boda", "Entrega en 24 h"],
    live: "EN VIVO",
    timecode: "9:16 · 00:14",
  },
  services: {
    eyebrow: "Qué hago",
    title: "Cuatro maneras de trabajar juntas",
    items: [
      { title: "Bodas", body: "La cobertura completa del día en vertical: la previa, los votos, el primer baile y la fiesta hasta el final.", from: "desde US$450" },
      { title: "Eventos privados", body: "Quinceañeros, pedidas de mano, aniversarios y bautizos. Mismo ojo, formato más corto.", from: "desde US$350" },
      { title: "Marcas y venues", body: "Contenido mensual para hoteles, wedding planners, floristas y salones que necesitan alimentar su feed.", from: "desde US$550 / mes" },
      { title: "Mentoría", body: "Asesoría 1:1 para creadoras que quieren entrar al mundo de las bodas y cobrar lo que vale su trabajo.", from: "US$120 / 90 min" },
    ],
  },
  work: {
    eyebrow: "Portafolio",
    title: "Tres bodas, tres mundos distintos",
    lede: "Una boda colonial de 180 invitados, una ceremonia de campo al atardecer y un fin de semana completo de boda destino. Desliza cada fila.",
    hint: "← Desliza para ver más →",
    cases: {
      colonial: { title: "Boda colonial", where: "Zona Colonial, Santo Domingo", specs: ["10 h de cobertura", "96 clips entregados", "3 reels editados", "Entregado en 24 h"] },
      campo: { title: "Boda de campo", where: "Jardín privado, ceremonia al atardecer", specs: ["8 h de cobertura", "74 clips entregados", "2 reels editados", "Entregado en 24 h"] },
      destino: { title: "Boda destino", where: "Fin de semana completo, tres días", specs: ["3 días de cobertura", "140+ clips entregados", "6 reels editados", "Entrega diaria"] },
    },
  },
  packages: {
    eyebrow: "Paquetes",
    title: "Elige cuánto del día quieres guardar",
    lede: "Los precios son de partida y en dólares. La cotización final depende de la fecha, el lugar y los extras que añadas abajo.",
    includes: "Incluye",
    names: ["Esencial", "Signature", "Destino"],
    from: "desde",
    rows: [
      { label: "Cobertura", values: ["6 horas", "10 horas", "3 días"] },
      { label: "Momentos", values: ["Ceremonia y recepción", "Previa completa hasta la fiesta", "Bienvenida, ensayo, boda y brunch"] },
      { label: "Clips en bruto", values: ["40–60", "80–120", "200+"] },
      { label: "Reels editados", values: ["1", "3", "6"] },
      { label: "Fotos verticales", values: ["20", "50", "100"] },
      { label: "Entrega", values: ["48 horas", "24 horas", "Cada día"] },
    ],
    priceLabel: "Precio",
    note: "Reserva con 30% de depósito · El resto una semana antes de la boda · Las fechas de temporada alta se agotan con 8–10 meses de anticipación.",
  },
  quote: {
    eyebrow: "Cotizar",
    title: "Arma tu cotización en un minuto",
    lede: "Marca lo que necesitas y te doy un precio de partida al instante. Al enviar, todo llega escrito a mi WhatsApp — sin formularios que se pierden.",
    name: "Tu nombre",
    namePh: "Nombre y apellido",
    date: "Fecha de la boda",
    place: "Lugar o venue",
    placePh: "Ej. Casa de Campo, La Romana",
    pkg: "Paquete",
    options: {
      esencial: "Esencial — 6 h — desde US$450",
      signature: "Signature — 10 h — desde US$795",
      destino: "Destino — 3 días — desde US$1,690",
      evento: "Evento privado — desde US$350",
      marca: "Marca o venue — desde US$550/mes",
    },
    extras: "Extras",
    addOns: {
      segunda: "Segunda creadora el día de la boda",
      previa: "Cobertura de la previa (día antes)",
      highlight: "Video highlight editado de 60 s",
      express: "Entrega express en 12 horas",
      venue: "Contenido extra para el venue",
      viaje: "Viaje fuera de Santo Domingo",
    },
    msg: "Cuéntame de tu boda",
    msgPh: "Cuántos invitados, quién es tu planner, qué momento no te puedes perder…",
    totalLabel: "Tu cotización, desde",
    sendWa: "Enviar por WhatsApp",
    sendMail: "Enviar por correo",
    book: "Agendar llamada de 15 min",
    subject: "Cotización de boda",
    saved: "Guardado. Te escribo hoy mismo.",
    saveError: "No se pudo guardar, pero el WhatsApp sí funciona.",
    disclaimer: "Precio de partida. La cotización final se confirma por escrito antes de reservar.",
  },
  message: {
    hi: "Hola Mela, me interesa tu contenido para mi boda.",
    name: "Nombre", date: "Fecha", place: "Lugar", pkg: "Paquete",
    extras: "Extras", est: "Estimado desde", notes: "Notas", none: "ninguno", tbd: "por definir",
  },
  process: {
    eyebrow: "Cómo trabajamos",
    title: "De la primera llamada a tu carpeta lista",
    steps: [
      { title: "Conversamos", body: "Quince minutos por videollamada para conocer tu boda, tu estilo y qué momentos no pueden faltar." },
      { title: "Reservas la fecha", body: "Firmamos un contrato simple y con 30% de depósito la fecha queda bloqueada solo para ti." },
      { title: "Un mes antes", body: "Coordino el cronograma con tu planner y armamos juntas la lista de tomas y las canciones que quieres." },
      { title: "El día", body: "Llego con tu equipo de maquillaje y no me voy hasta que se apaguen las luces. Grabo sin interrumpir a nadie." },
      { title: "Al día siguiente", body: "Recibes una carpeta organizada por momentos, más los reels editados, listos para subir desde tu teléfono." },
    ],
  },
  about: {
    eyebrow: "Sobre mí",
    title: "Soy la invitada que se acuerda de grabarlo todo",
    body: [
      "Empecé grabando las bodas de mis amigas con el teléfono, porque nadie estaba capturando las cosas pequeñas: la mano del papá temblando, el brindis que nadie planeó, las damas descalzas a las dos de la mañana.",
      "Hoy hago eso mismo a tiempo completo. Trabajo en República Dominicana y viajo a donde haga falta. No sustituyo a tu fotógrafo ni a tu videógrafo: yo soy la que te entrega el día siguiente lo que ellos te darán en seis meses.",
    ],
    photoAlt: "Mela, creadora de contenido de bodas, de brazos cruzados sobre fondo gris",
  },
  testimonial: {
    eyebrow: "Lo que dicen",
    quote: "«Cada pequeño momento lo vuelve gigante.»",
    cite: "@rolandocaceresm · comentario en Instagram",
  },
  faq: {
    eyebrow: "Preguntas",
    title: "Lo que toda novia pregunta primero",
    items: [
      { q: "¿En qué te diferencias de mi fotógrafo o mi videógrafo?", a: "Ellos hacen la pieza de arte: la entrega es cuidada, editada y llega en semanas o meses. Yo hago el contenido vivo: vertical, rápido, con textura de teléfono, y lo tienes en las manos al día siguiente. Los tres trabajamos juntos el mismo día sin estorbarnos." },
      { q: "¿Cuándo recibo el material?", a: "En 24 horas para los paquetes Signature y Destino, en 48 para el Esencial. Llega en una carpeta de Google Drive organizada por momentos, más los reels ya editados en formato listo para publicar." },
      { q: "¿Viajas fuera del país?", a: "Sí. Cubro toda la República Dominicana y viajo a bodas destino en el Caribe, Estados Unidos y Europa. Fuera de Santo Domingo se añade el viaje; internacional se cotiza aparte e incluye vuelo y alojamiento." },
      { q: "¿Cómo reservo mi fecha?", a: "Con un contrato simple y 30% de depósito. Hasta que no entra el depósito la fecha sigue abierta para otras parejas, y las fechas de temporada alta se van con 8 a 10 meses de anticipación." },
      { q: "¿Con qué grabas?", a: "iPhone de última generación con lentes y estabilizador, micrófonos inalámbricos para los votos y los discursos, y luz portátil para la fiesta. Es el equipo que produce la textura que funciona en redes." },
      { q: "¿Puedes hacer contenido para mi venue o mi marca?", a: "Sí. Trabajo con hoteles, wedding planners, floristas y salones con paquetes mensuales de contenido. Escríbeme y armamos algo a la medida de tu calendario." },
    ],
  },
  contact: {
    eyebrow: "Hablemos",
    title: "Cuéntame de tu boda",
    lede: "Contesto todos los mensajes personalmente, normalmente el mismo día. Si tu fecha ya está tomada, te recomiendo a alguien de confianza.",
    mail: "Correo",
    call: "Llamada",
    callValue: "Agendar 15 minutos",
  },
  footer: "Content by Mela · Contenido de bodas · República Dominicana y destino",
  dock: { wa: "WhatsApp", quote: "Cotizar", pricing: "Precios" },
};

export type MelaContent = typeof es;

const en: MelaContent = {
  nav: { work: "Work", pkg: "Packages", proc: "Process", about: "About", faq: "FAQ", cta: "Get a quote" },
  hero: {
    eyebrow: "Wedding content creator · Dominican Republic & destination",
    titleA: "Your wedding, posted ",
    titleEm: "before",
    titleB: " the party ends.",
    lede: "I film your day vertically, with a guest's eye and an editor's judgment. No waiting six months: your footage lands in your hands the next day, ready to post.",
    cta1: "Message me on WhatsApp",
    cta2: "See packages and pricing",
    specs: ["Native 9:16 vertical", "60–120 clips per wedding", "Delivered in 24 h"],
    live: "LIVE",
    timecode: "9:16 · 00:14",
  },
  services: {
    eyebrow: "What I do",
    title: "Four ways we can work together",
    items: [
      { title: "Weddings", body: "Full vertical coverage of the day: getting ready, the vows, the first dance and the party until the lights come on.", from: "from US$450" },
      { title: "Private events", body: "Quinceañeras, proposals, anniversaries and christenings. Same eye, shorter format.", from: "from US$350" },
      { title: "Brands and venues", body: "Monthly content for hotels, wedding planners, florists and venues that need to keep a feed alive.", from: "from US$550 / month" },
      { title: "Mentoring", body: "One-on-one coaching for creators who want to break into weddings and charge what their work is worth.", from: "US$120 / 90 min" },
    ],
  },
  work: {
    eyebrow: "Portfolio",
    title: "Three weddings, three different worlds",
    lede: "A 180-guest colonial wedding, a garden ceremony at golden hour and a full destination weekend. Swipe each row.",
    hint: "← Swipe to see more →",
    cases: {
      colonial: { title: "Colonial wedding", where: "Colonial Zone, Santo Domingo", specs: ["10 h coverage", "96 clips delivered", "3 edited reels", "Delivered in 24 h"] },
      campo: { title: "Garden wedding", where: "Private garden, golden-hour ceremony", specs: ["8 h coverage", "74 clips delivered", "2 edited reels", "Delivered in 24 h"] },
      destino: { title: "Destination wedding", where: "Full three-day weekend", specs: ["3 days coverage", "140+ clips delivered", "6 edited reels", "Delivered daily"] },
    },
  },
  packages: {
    eyebrow: "Packages",
    title: "Choose how much of the day you want to keep",
    lede: "Prices are starting points, in US dollars. Your final quote depends on the date, the venue and the add-ons you pick below.",
    includes: "Includes",
    names: ["Essential", "Signature", "Destination"],
    from: "from",
    rows: [
      { label: "Coverage", values: ["6 hours", "10 hours", "3 days"] },
      { label: "Moments", values: ["Ceremony and reception", "Getting ready through the party", "Welcome, rehearsal, wedding and brunch"] },
      { label: "Raw clips", values: ["40–60", "80–120", "200+"] },
      { label: "Edited reels", values: ["1", "3", "6"] },
      { label: "Vertical stills", values: ["20", "50", "100"] },
      { label: "Delivery", values: ["48 hours", "24 hours", "Every day"] },
    ],
    priceLabel: "Price",
    note: "Book with a 30% deposit · Balance one week before the wedding · Peak-season dates go 8–10 months out.",
  },
  quote: {
    eyebrow: "Get a quote",
    title: "Build your quote in a minute",
    lede: "Tick what you need and I'll give you a starting price right away. When you send it, everything arrives written out on my WhatsApp — no forms that get lost.",
    name: "Your name",
    namePh: "First and last name",
    date: "Wedding date",
    place: "Venue or location",
    placePh: "e.g. Casa de Campo, La Romana",
    pkg: "Package",
    options: {
      esencial: "Essential — 6 h — from US$450",
      signature: "Signature — 10 h — from US$795",
      destino: "Destination — 3 days — from US$1,690",
      evento: "Private event — from US$350",
      marca: "Brand or venue — from US$550/month",
    },
    extras: "Add-ons",
    addOns: {
      segunda: "Second creator on the wedding day",
      previa: "Rehearsal-day coverage",
      highlight: "Edited 60-second highlight video",
      express: "Express delivery in 12 hours",
      venue: "Extra content for the venue",
      viaje: "Travel outside Santo Domingo",
    },
    msg: "Tell me about your wedding",
    msgPh: "Guest count, who your planner is, the one moment you cannot miss…",
    totalLabel: "Your quote, from",
    sendWa: "Send on WhatsApp",
    sendMail: "Send by email",
    book: "Book a 15-min call",
    subject: "Wedding content quote",
    saved: "Saved. I'll write to you today.",
    saveError: "Couldn't save it, but WhatsApp still works.",
    disclaimer: "Starting price. Your final quote is confirmed in writing before booking.",
  },
  message: {
    hi: "Hi Mela, I'm interested in your content for my wedding.",
    name: "Name", date: "Date", place: "Venue", pkg: "Package",
    extras: "Add-ons", est: "Estimated from", notes: "Notes", none: "none", tbd: "to be confirmed",
  },
  process: {
    eyebrow: "How we work",
    title: "From the first call to your finished folder",
    steps: [
      { title: "We talk", body: "Fifteen minutes on video to get to know your wedding, your style and the moments that cannot be missed." },
      { title: "You book the date", body: "We sign a simple contract and a 30% deposit holds the date for you alone." },
      { title: "One month out", body: "I coordinate the timeline with your planner and we build the shot list and the songs you want together." },
      { title: "The day", body: "I arrive with your glam team and I don't leave until the lights come on. I film without interrupting anyone." },
      { title: "The next day", body: "You get a folder organised by moment, plus the edited reels, ready to post straight from your phone." },
    ],
  },
  about: {
    eyebrow: "About me",
    title: "I'm the guest who remembers to film everything",
    body: [
      "I started filming my friends' weddings on my phone, because nobody was capturing the small things: her dad's hand shaking, the toast nobody planned, the bridesmaids barefoot at two in the morning.",
      "Today I do exactly that full time. I'm based in the Dominican Republic and I travel wherever the wedding is. I don't replace your photographer or your videographer: I'm the one who hands you tomorrow what they'll give you in six months.",
    ],
    photoAlt: "Mela, wedding content creator, arms folded against a grey backdrop",
  },
  testimonial: {
    eyebrow: "Kind words",
    quote: "“She makes every small moment feel enormous.”",
    cite: "@rolandocaceresm · Instagram comment (translated)",
  },
  faq: {
    eyebrow: "FAQ",
    title: "What every bride asks first",
    items: [
      { q: "How are you different from my photographer or videographer?", a: "They make the art piece: carefully edited, delivered in weeks or months. I make the living content: vertical, fast, with that phone texture, in your hands the next day. All three of us work the same day without getting in each other's way." },
      { q: "When do I get my footage?", a: "Within 24 hours for Signature and Destination, 48 for Essential. It arrives as a Google Drive folder organised by moment, plus the edited reels in a ready-to-post format." },
      { q: "Do you travel abroad?", a: "Yes. I cover the whole Dominican Republic and travel to destination weddings across the Caribbean, the United States and Europe. Outside Santo Domingo adds a travel fee; international is quoted separately and includes flights and accommodation." },
      { q: "How do I book my date?", a: "With a simple contract and a 30% deposit. Until the deposit lands the date stays open to other couples, and peak-season dates go 8 to 10 months in advance." },
      { q: "What do you film with?", a: "A latest-generation iPhone with lenses and a gimbal, wireless mics for the vows and the speeches, and a portable light for the party. It's the kit that produces the texture that actually works on social." },
      { q: "Can you create content for my venue or brand?", a: "Yes. I work with hotels, wedding planners, florists and venues on monthly content packages. Write to me and we'll build something around your calendar." },
    ],
  },
  contact: {
    eyebrow: "Let's talk",
    title: "Tell me about your wedding",
    lede: "I answer every message myself, usually the same day. If your date is already taken, I'll point you to someone I trust.",
    mail: "Email",
    call: "Call",
    callValue: "Book 15 minutes",
  },
  footer: "Content by Mela · Wedding content · Dominican Republic and destination",
  dock: { wa: "WhatsApp", quote: "Quote", pricing: "Pricing" },
};

export const melaContent: Record<MelaLocale, MelaContent> = { es, en };
